# Generated by Django 4.2.2 on 2023-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
