# Generated by Django 4.2.2 on 2023-06-26 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_alter_mycustomuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('descritpion', models.CharField(max_length=256)),
                ('p_type', models.CharField(choices=[('FE', 'Front-end'), ('BE', 'Back-end'), ('Android', 'Android'), ('IOS', 'IOS')], max_length=7)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
