# Generated by Django 4.2.2 on 2023-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_mycustomuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
