# Generated by Django 4.2.2 on 2023-06-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_mycustomuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descritpion',
            new_name='description',
        ),
    ]
