# Generated by Django 4.2.2 on 2023-07-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
